<?php

/**
 * Implementation of hook_hosting_tasks
 */
function hosting_tasks_extra_hosting_tasks() {
  $tasks = array();

  $tasks['site']['flush_cache'] = array(
    'title' => t('Flush all caches'),
    'description' => t('Flushes all caches on the site.'),
  );
  $tasks['site']['rebuild_registry'] = array(
    'title' => t('Rebuild registry'),
    'description' => t('Rebuilds the registry and flushes all caches on the site.'),
  );
  $tasks['site']['run_cron'] = array(
    'title' => t('Run cron'),
    'description' => t('Runs cron on the site.'),
  );
  $tasks['site']['update'] = array(
    'title' => t('Update'),
    'description' => t('Run updates on this site.'),
    'dialog' => TRUE,
    );

  return $tasks;
}


/**
 * Implementation of hook_perm()
 */
function hosting_tasks_extra_perm() {
  return array(
    'create rebuild_registry task',
    'create flush_cache task',
    'create run_cron task',
    'create update task',
  );
}

